services:
  arbitra:
    image: arbitra
    build:
      context: .
      dockerfile: Dockerfile
    container_name: arbitra-container
    volumes:
      - ./wwwroot/Data:/app/wwwroot/Data
    ports:
      - "8080:8080"